### ISSUE TITLE
Add some simple "Out of Mech" play rules

### ISSUE THREAD

**Issue by Icosahunter** [mechtronica/mechtronica.net#56] opened 2023-07-29 15:29 UTC
- [x] Hand-to-hand combat rules
- [ ] (Add more stuff here?)

**Comment by infinitymdm** [comment] 2023-07-29 15:40
I'll work on out-of-mech combat rules based on the old "Opportunity Points" mechanic we discussed on discord, with each turn consisting of movement + one action (stat roll).

**Comment by infinitymdm** [comment] 2023-09-02 16:29
Duplicate of #57

**Closed as completed** 2023-09-02 16:29 UTC
